---
development:
  dialect: postgres
  database: blog_app_development
  user: oporanski
  password: NimalidlSk201(
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://oporanski:NimalidlSk201(@127.0.0.1:5432/blog_app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://oporanski:NimalidlSk201(@127.0.0.1:5432/blog_app_production?sslmode=disable"}}
